// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3Yc0k15RTCM9zhCu6Xu_LyL2Y8X-Qcrc',
    appId: '1:90348986288:web:56fd64b9163b7e017a8075',
    messagingSenderId: '90348986288',
    projectId: 'iot-air-quality-38ff3',
    authDomain: 'iot-air-quality-38ff3.firebaseapp.com',
    storageBucket: 'iot-air-quality-38ff3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc2VPlKA_Ue6mXcAg8IM9afaKsSbO9biA',
    appId: '1:90348986288:android:ff45b25351d875e97a8075',
    messagingSenderId: '90348986288',
    projectId: 'iot-air-quality-38ff3',
    storageBucket: 'iot-air-quality-38ff3.appspot.com',
    databaseURL:
        'https://iot-air-quality-38ff3-default-rtdb.europe-west1.firebasedatabase.app', // Add this line
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUbDVnJkOT7lN1T-bzNSmv7qwrKIA98U0',
    appId: '1:90348986288:ios:7c27c74b91c4c33f7a8075',
    messagingSenderId: '90348986288',
    projectId: 'iot-air-quality-38ff3',
    storageBucket: 'iot-air-quality-38ff3.appspot.com',
    iosBundleId: 'com.example.airQuality',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUbDVnJkOT7lN1T-bzNSmv7qwrKIA98U0',
    appId: '1:90348986288:ios:d2f5444397f0ca857a8075',
    messagingSenderId: '90348986288',
    projectId: 'iot-air-quality-38ff3',
    storageBucket: 'iot-air-quality-38ff3.appspot.com',
    iosBundleId: 'com.example.airQuality.RunnerTests',
  );
}
